### PR TITLE
Remove publish_rate parameter

### PR DESCRIPTION
**Pull request by tonynajjar**
It was removed https://github.com/ros-controls/ros2_controllers/pull/468

### CODE REVIEW

**Comment by ahcorde** [comment]
CI is failing, the `service_msgs` package was added 3 weeks ago https://github.com/ros2/rcl_interfaces/commits/rolling/service_msgs and it was released last week, maybe a package that uses this dependency is not released yet and that's why is failing?

**Comment by tonynajjar** [comment]
just to clarify, are you asking me the question? :smile:

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@bmagyar or @destogl can you relaunch the Github actions ?

**Comment by ahcorde** [comment]
> just to clarify, because that's unrelated to my PR, are you asking me the question? smile

This was not a question, it was a clarification, but for some reason I added `?`.  Let's relaunch CI

**Pull request merged**
