### PR TITLE
set the robot description parameter

### PR DESCRIPTION
**Pull request by annaborn**
This merge resolves the issue with robot description parameter in controller manager and controllers.
Some custom controllers require information about robot description, which are available normally over a parameter of controller manager and controllers in the ros2 control. However, this parameter was missing, if the controller manager (as well controllers) is started over gazebo ros2 control. Therefore, the custom controllers could not be used/tested with the gazebo.
I tested this code with my custom controllers. 

If you have some remarks, I would be glad to introduce some improvement.

Here is an output of parameter list before (without robot description parameter):

```
/controller_manager:
  forward_position_controller.type
  joint_state_broadcaster.type
  qos_overrides./clock.subscription.depth
  qos_overrides./clock.subscription.durability
  qos_overrides./clock.subscription.history
  qos_overrides./clock.subscription.reliability
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  update_rate
  use_sim_time

/forward_position_controller:
  interface_name
  joints
  qos_overrides./clock.subscription.depth
  qos_overrides./clock.subscription.durability
  qos_overrides./clock.subscription.history
  qos_overrides./clock.subscription.reliability
  update_rate
  use_sim_time

/joint_state_broadcaster:
  extra_joints
  interfaces
  joints
  map_interface_to_joint_state.effort
  map_interface_to_joint_state.position
  map_interface_to_joint_state.velocity
  qos_overrides./clock.subscription.depth
  qos_overrides./clock.subscription.durability
  qos_overrides./clock.subscription.history
  qos_overrides./clock.subscription.reliability
  update_rate
  use_local_topics
  use_sim_time
```

And here is the output with the fix:
```
/controller_manager:
  forward_position_controller.type
  joint_state_broadcaster.type
  qos_overrides./clock.subscription.depth
  qos_overrides./clock.subscription.durability
  qos_overrides./clock.subscription.history
  qos_overrides./clock.subscription.reliability
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  robot_description
  update_rate
  use_sim_time

/forward_position_controller:
  interface_name
  joints
  qos_overrides./clock.subscription.depth
  qos_overrides./clock.subscription.durability
  qos_overrides./clock.subscription.history
  qos_overrides./clock.subscription.reliability
  robot_description
  update_rate
  use_sim_time

/joint_state_broadcaster:
  extra_joints
  interfaces
  joints
  map_interface_to_joint_state.effort
  map_interface_to_joint_state.position
  map_interface_to_joint_state.velocity
  qos_overrides./clock.subscription.depth
  qos_overrides./clock.subscription.durability
  qos_overrides./clock.subscription.history
  qos_overrides./clock.subscription.reliability
  robot_description
  update_rate
  use_local_topics
  use_sim_time
```

To get the robot description parameter value over cli returns the correct urdf.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
check format https://github.com/ros-controls/gazebo_ros2_control/actions/runs/7762574839/job/21217428831?pr=277

**Comment by annaborn** [comment]
> check format https://github.com/ros-controls/gazebo_ros2_control/actions/runs/7762574839/job/21217428831?pr=277
@ahcorde 
The trailing white space was removed. 
If I see it correctly, this was the single issue, right?

**Comment by annaborn** [comment]
@ahcorde @christophfroehlich 
Hey guys! 
What is the procedure to finish the PR? Do you need smth from my side?
The requested changes are done.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport iron master

**Pull request merged**
