### PR TITLE
Removed unused var

### PR DESCRIPTION
**Pull request by ahcorde**
Related with this comment https://github.com/ros-controls/gazebo_ros2_control/pull/177#issuecomment-1674842288

### CODE REVIEW

**Review by christophfroehlich — APPROVED** [review]
Thanks for the immediate fix :)

**Comment by ahcorde** [comment]
@bmagyar or @destogl can you approved this too?

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
Less code, happier maintainers.

We can always revert it if we realize we need it again

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble

**Pull request merged**
