### PR TITLE
[Backport Foxy] Support for mimic joints and example with gripper.

### PR DESCRIPTION
**Pull request by leander-dsouza**
This PR backports the mimic features set in the master branch #107 and #109 back to foxy.

### CODE REVIEW

**Comment by leander-dsouza** [comment]
Hello, maintainers,

Could you please approve the workflow of my PR?

**Comment by leander-dsouza** [comment]
Hello maintainers,

Could you please review my PR of backporting the mimicking changes from `rolling` to `foxy`?

**Review by bmagyar — APPROVED** [review]
I'm happy with this to be backported to Foxy.

@ahcorde or @destogl please provide a second opinion and merge if agree

**Review by ahcorde — CHANGES_REQUESTED** [review]
@leander-dsouza or @destogl can you fix the conflicts?

**Comment by leander-dsouza** [comment]
Yes, sure I will fix the conflicts @ahcorde.

**Comment by leander-dsouza** [comment]
@ahcorde I have resolved the merge conflicts.

**Review by ahcorde — CHANGES_REQUESTED** [review]
linters: https://github.com/ros-controls/gazebo_ros2_control/runs/7946325609?check_suite_focus=true

**Review by ahcorde — APPROVED** [review]
Thank you for iterating! Do you have any plans to do the same in `gz_ros2_control`?

**Pull request merged**
