### PR TITLE
Load the URDF to the resource_manager before parsing it to CM 

### PR DESCRIPTION
**Pull request by saikishor**
These changes are needed after the merging of https://github.com/ros-controls/ros2_control/pull/1271 and https://github.com/ros-controls/ros2_control/pull/1272. It seems like the gazebo_ros2_control doesn't load the URDF into the resource manager, and this is causing the CM services not to start.

However, loading the URDF with the [`load_urdf`](https://github.com/ros-controls/ros2_control/blob/3309c6dbaf4ab5140d13908bedb6fb471c422498/hardware_interface/src/resource_manager.cpp#L759-L796) method will probably fail, because this method originally loads and initializes the hardware interfaces and this step might probably fail. For this reason, I'm catching the exception here, but the overall behaviour will work.

If approved, this will need backport to Iron and Humble

Needs: https://github.com/ros-controls/ros2_control/pull/1301
Fixes: https://github.com/ros-controls/ros2_control/issues/1299

### CODE REVIEW

**Comment by christophfroehlich** [comment]
Unfortunately, this doesn't work
> $ ros2 launch ros2_control_demo_example_9 rrbot_gazebo_classic.launch.py
> ...
> [gzserver-1] [INFO] [1705433169.698759862] [resource_manager]: Loading hardware 'RRBot' 
> [gzserver-1] [ERROR] [1705433169.699241795] [gazebo_ros2_control]: Error initializing URDF to resource manager!
> [gzserver-1] [INFO] [1705433169.708220862] [gazebo_ros2_control]: Loading joint: joint1
> [gzserver-1] [INFO] [1705433169.708324807] [gazebo_ros2_control]:       State:
> [gzserver-1] [INFO] [1705433169.708352546] [gazebo_ros2_control]:                position
> [gzserver-1] [INFO] [1705433169.708586986] [gazebo_ros2_control]:       Command:
> [gzserver-1] [INFO] [1705433169.708603957] [gazebo_ros2_control]:                position
> [gzserver-1] [INFO] [1705433169.708978881] [gazebo_ros2_control]: Loading joint: joint2
> [gzserver-1] [INFO] [1705433169.709003788] [gazebo_ros2_control]:       State:
> [gzserver-1] [INFO] [1705433169.709010914] [gazebo_ros2_control]:                position
> [gzserver-1] [INFO] [1705433169.709113025] [gazebo_ros2_control]:       Command:
> [gzserver-1] [INFO] [1705433169.709124671] [gazebo_ros2_control]:                position

and gazebo isn't even launched.

**Comment by saikishor** [comment]
> Unfortunately, this doesn't work
> > $ ros2 launch ros2_control_demo_example_9 rrbot_gazebo_classic.launch.py
> > ...
> > [gzserver-1] [INFO] [1705433169.698759862] [resource_manager]: Loading hardware 'RRBot' 
> > [gzserver-1] [ERROR] [1705433169.699241795] [gazebo_ros2_control]: Error initializing URDF to resource manager!
> > [gzserver-1] [INFO] [1705433169.708220862] [gazebo_ros2_control]: Loading joint: joint1
> > [gzserver-1] [INFO] [1705433169.708324807] [gazebo_ros2_control]:       State:
> > [gzserver-1] [INFO] [1705433169.708352546] [gazebo_ros2_control]:                position
> > [gzserver-1] [INFO] [1705433169.708586986] [gazebo_ros2_control]:       Command:
> > [gzserver-1] [INFO] [1705433169.708603957] [gazebo_ros2_control]:                position
> > [gzserver-1] [INFO] [1705433169.708978881] [gazebo_ros2_control]: Loading joint: joint2
> > [gzserver-1] [INFO] [1705433169.709003788] [gazebo_ros2_control]:       State:
> > [gzserver-1] [INFO] [1705433169.709010914] [gazebo_ros2_control]:                position
> > [gzserver-1] [INFO] [1705433169.709113025] [gazebo_ros2_control]:       Command:
> > [gzserver-1] [INFO] [1705433169.709124671] [gazebo_ros2_control]:                position
> 
> and gazebo isn't even launched. 

Strange! Ok thanks for the feedback. I'll cross-check again.

**Comment by saikishor** [comment]
@christophfroehlich If this PR: https://github.com/ros-controls/ros2_control/pull/1301 gets merged. We won't be needing this PR

**Review by bmagyar — APPROVED** [review]

**Comment by ahcorde** [comment]
CI is not passing because of the new API in `ros2_control`. @bmagyar when do you have plant to do a new release?

**Comment by saikishor** [comment]
@ahcorde Bence tagged and released the required changes in the distros

**Comment by ahcorde** [comment]
With testing package CI is passing, merging it

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
